### ISSUE TITLE
OPTIONS ORDER IS NOT SAME FOR EVERYONE

### ISSUE THREAD

**Issue by future-XD** [skndash96/jeeadv-scorecard#1]
tit le

**Comment by Aedon** [comment]
[Read his method](https://new.reddit.com/r/JEENEETards/comments/1d52sle/jee_adv_2024_scorecard_generator_is_not_possible/)

**Comment by skndash96** [comment]
Yes the options order is shuffled for everyone. But the image link is same for everyone for a specific option.

Take for example,
My response sheet: for a particular question
A. 1 and image link `q1_o3.jpg`
B. 2 and image link `q1_o2.jpg`
C. 3 and image link `q1_o1.jpg`
D. 4 and image link `q1_o4.jpg`

Now your response sheet may have
A. 3 and image link `q1_o1.jpg`
B. 1 and image link `q1_o3.jpg`
C. 2 and image link `q1_o2.jpg`
D. 4 and image link `q1_o4.jpg`

You see image link is same for a particular option for everyone.
That's how it works.
